Strict set CwF and TypeCat structures
unimath2019-tt/TypeTheory pull request #3
Opened 2019-04-20 17:04 UTC by andreaslyn

Cherry pick commits on Strict Set from the UniMath workshop.

2019-04-20 17:28 UTC, andreaslyn commented
This PR supersedes https://github.com/unimath2019-tt/TypeTheory/pull/1.

2019-04-21 16:31 UTC, mortberg requested changes
This is very nice! The only changes left to do is some refactoring of the `guniverse` structure and that this is a split type-category. The latter should be essentially the same as proving that it is a CwF.

2019-04-21 16:31 UTC, mortberg commented on TypeTheory/Instances/StrictSet.v
> +Defined.
It should be possible to prove that this is a split type-category:

https://github.com/unimath2019-tt/TypeTheory/blob/dev/TypeTheory/ALV1/TypeCat.v#L178

That is what really is different between V and HSET.

2019-04-21 16:31 UTC, mortberg commented on TypeTheory/Instances/StrictSet.v
> +Defined.
Very nice!

2019-04-21 16:31 UTC, mortberg commented on TypeTheory/Instances/StrictSet.v
> +  ∑ (A : pre_guniverse), is_guniverse A.
Please change this definition to only say that it is a set universe closed under Pi and Sigma. It is not necessary that it has bool/empty.

2019-04-22 14:41 UTC, andreaslyn commented on TypeTheory/Instances/StrictSet.v
> +Defined.
> This is very nice! The only changes left to do is some refactoring of the `guniverse` structure and that this is a split type-category. The latter should be essentially the same as proving that it is a CwF.

This is fixed in the new commit.

2019-04-22 15:20 UTC, mortberg commented on TypeTheory/Instances/StrictSet.v
> +Lemma VSET_is_split_typecat : is_split_typecat VSET_TypeCat.
Very nice!

2019-04-22 15:30 UTC, mortberg commented on TypeTheory/Instances/StrictSet.v
> +  ∑ (A : pre_guniverse), is_guniverse A.
Actually, how about not packaging this up at all? The proofs below would be a bit slicker if you don't have to unpack the `guniverse` structure all the time.

So it would be something like (I haven't typechecked this in Coq, so it is probably full of typos):
```
Definition V : UU := ∑ (A : hSet), A → hSet.
Definition pr1V : V -> hSet := @pr1 hSet _.
Coercion pr1V : V >-> hSet.
Definition El {A : V} : A → hSet := (pr2 A).

Definition V_sigma {A : pre_guniverse} : UU := ∏ (a : A) (b : El a → A), A.
Variable V_sigma_El (A : pre_guniverse) : 
  ∏ (a : A) (b : El a → A), El (V_sigma a b)  = (∑ (x : El a), El (b x))%set.

...
```

You could potentially even use lowercase \sigma and \pi for the ones in V.

2019-04-24 22:59 UTC, andreaslyn commented on TypeTheory/Instances/StrictSet.v
> +  ∑ (A : pre_guniverse), is_guniverse A.
I have unpacked the guniverse. What do you mean with "lowercase \sigma and \pi for the ones in V"?

2019-04-25 00:14 UTC, mortberg commented on TypeTheory/Instances/StrictSet.v
> +  ∑ (A : pre_guniverse), is_guniverse A.
I just meant to use the greek characters. Anyway it's not important

2019-04-25 00:22 UTC, mortberg commented
This looks good to me now! Just add a header to the file saying what it contains and who wrote it. Then you can make a PR to TypeTheory.

2019-05-04 09:18 UTC, andreaslyn commented
This has been merged into UniMath/TypeTheory.

2019-05-04 09:18 UTC, closed without merging