Set CwF and TypeCat structures
unimath2019-tt/TypeTheory pull request #4
Opened 2019-04-20 17:25 UTC by andreaslyn

Cherry pick commits on Sets.v from the UniMath workshop.

2019-04-20 17:31 UTC, andreaslyn commented
This PR supersedes https://github.com/unimath2019-tt/TypeTheory/pull/2.

2019-04-21 16:25 UTC, mortberg requested changes
I read through the code now and had a few comments. Let me know if you need help with anything.

2019-04-21 16:25 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +Written by: Anders Mörtberg, 2017
Please update

2019-04-21 16:25 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +Defined.
I think you can remove all of the `unfold`, `cbn` and `simpl` from this and many of the other proofs. This makes the final proof scripts easier to read as they will mainly be `use tpair`, `intros` and `exact`.

2019-04-21 16:25 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +Defined.
I think this can be solved by simply typing `easy` or just `repeat (split; easy)`:

https://github.com/UniMath/UniMath/blob/master/UniMath/MoreFoundations/Tactics.v#L9

2019-04-21 16:25 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +Admitted.
How about stating the things that are provable as separate lemmas?

2019-04-21 16:25 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +         Admitted.
Let me know if you want me to finish these proofs or will you do it?

2019-04-22 15:45 UTC, andreaslyn commented
> I read through the code now and had a few comments. Let me know if you need help with anything.

I have polished it a bit now.

2019-04-22 15:47 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +Definition SET_ctx_proj {Γ : HSET} {A : Γ ⊢} : Γ ⋆ A --> Γ.
When the proof is just a standard function I typically define it directly:
```
Definition SET_ctx_proj {Γ : HSET} {A : Γ ⊢} : Γ ⋆ A --> Γ := pr1.
```

You might need to put an @ and give some argument explicitly

2019-04-22 15:49 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +This files proves that HSET (almost) forms a type category ([HSET_TypeCat]). As the
The "(almost)" can be removed

2019-04-22 15:51 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +(* The following cannot be completed
Can you please add "because SET is not an h-set"

2019-04-22 15:51 UTC, mortberg commented on TypeTheory/Instances/Sets.v
> +Definition SET_CwF : cwf_struct (SET).
Remove parantheses are "SET". :-)

2019-04-22 15:52 UTC, mortberg commented
> > I read through the code now and had a few comments. Let me know if you need help with anything.
> 
> I have polished it a bit now.

Great! I made a few small comments. Once you have addressed these I think we can open a PR to UniMath/TypeTheory with this file

2019-04-24 21:13 UTC, andreaslyn commented
I have worked on the comments now. I just realized that we are missing quite a bit of operations (subst_type, ctx_ext, ...) and equations (subst_type_id, subst_type_comp, ...) that we claim to have in the beginning of the file. Maybe we should add this before opening a PR to UniMath/TypeTheory?

2019-04-25 00:18 UTC, mortberg commented
> I have worked on the comments now. I just realized that we are missing quite a bit of operations (subst_type, ctx_ext, ...) and equations (subst_type_id, subst_type_comp, ...) that we claim to have in the beginning of the file. Maybe we should add this before opening a PR to UniMath/TypeTheory?

Many of these are just proved by refl... But it might be nice to state them. So either add the statements or change the comment in the beginning of the file.

2019-04-26 15:55 UTC, mortberg commented
Great! Is this finished now? If so please make a PR to TypeTheory.

2019-04-29 15:53 UTC, andreaslyn commented
Closing this pull request because it has been merged into UniMath/TypeTheory https://github.com/UniMath/TypeTheory/pull/154.

2019-04-29 15:53 UTC, closed without merging